### ISSUE TITLE
Link is not working properly in the body editor on card block

### ISSUE THREAD

**Issue by zainabD** [asu-ke-web-services/UDS-WordPress-Theme#157]
When I go to the body editor and try to insert a link, the field flashes on and off and never let me add a link.
It could be an ACF issue, if so, can we hide the link option from the editor for now?

Screen Recording 2021-03-24 at 9.47.45 AM.mov

**Comment by wmcconnell** [comment]
While going through our issues to do some cleanup, I decided to take a quick look at this issue. Making some notes here so I don't forget:

- I can't replicate this issue on any Mac browser, but I do remember Zainab showing me (and seeing that video). It may have been fixed by an update to Gutenberg/WordPress
- Regardless, I don't believe that the standards even allow links in the body text of a card. There's a specific place for links in the card design, and I don't think they're supposed to be anywhere else
- This fix should just be a matter of using a more basic toolbar in the WYSIWYG editor. In fact, I think I already made one just for this purpose, the `uds-wp-minimal` toolbar that doesn't have the link option.

I have this working in a test branch already, so I'll take care of it. Assigning this to myself.
