### ISSUE TITLE
Action hooks for easier child theme templating

### ISSUE THREAD

**Issue by SteveRyan-ASU** [asu-ke-web-services/UDS-WordPress-Theme#54]
When adding templates to a child theme of **UDS-WordPress**, it will be helpful to have a series of defined places within the parent theme upon which to add code. Within the WordPress ecosystem, this is typically done by the simple insertion of a "hook" in a documented place within the theme or plugin. Child themes or additional plugins can then take advantage of this prescribed architecture by inserting a template or custom piece of code in a safe and secure manner. 

Action hook overview: https://kinsta.com/blog/wordpress-hooks/ (Long read.)

I wanted to raise this issue as a way to introduce the topic to the group and to think through a way to:

- name the hooks correctly
- talk briefly about the risk (or lack thereof) that inserting these pose to the end product
- figure out how to document their existence someplace.

**Comment by SteveRyan-ASU** [comment]
For the project that I am working on right now, I can foresee a use case for two such "hooks."

- **Hook 1: After Header** - fires immediately after the closing `</header><!-- end #asu-header -->` statement in `header.php` That would allow for a small banner or other alert mechanism to be added before a potential hero image across multuple pages on the site. 
- **Hook 2: Before Footer** - fires immediately before the closing global `<footer>` tag in `footer.php` This would allow for a persistent "block" of code to appear across multiple pages as a closing feature for a site.

In addition, I would like to raise the possibility of a third hook, but perhaps leaving it undocumented for the moment.
- **Hook 3: Before Footer Columns** - would fire immediately before the `<div id="wrapper-footer-columns">` also in `footer.php`. In conjunction with the theme option to turn off the native footer column feature, this would be a handy way to "roll your own footer columns" either using widgets or other means.

**Comment by SteveRyan-ASU** [comment]
Adding a hook to the parent theme should have exactly zero effect on the output when used as a standalone theme.

**Comment by SteveRyan-ASU** [comment]
Example from the current furi.engineering.asu.edu site.
The hook in the header would allow for the creation of a feature like this one.
![image](https://user-images.githubusercontent.com/2085753/98631633-1296ff80-22db-11eb-8f55-15dd3e8e6b29.png)

... and the hook above the footer would allow for the insertion of a feature like this near the footer.
![image](https://user-images.githubusercontent.com/2085753/98631691-2fcbce00-22db-11eb-9b9c-169100f81376.png)

**Comment by SteveRyan-ASU** [comment]
Referencing issue #30, this would also be another valid approach to building the proposed banner alert mechanism. Great minds think alike @wmcconnell 😁

**Comment by nathan-rollins** [comment]
I whole-heartedly support these ideas. Hooks are a fantastic way to make a theme or custom plugin easily extendable in a standardized, officially supported manner. It also make maintenance and troubleshooting simpler.

But it just occurred to me that we may still need a base theme solution for inserting special content sections globally across our websites. For instance, when we needed to add the Coronavirus banner on our websites, would it be preferable to be able to add that global banner via a widget block in the standard theme settings or by activating a child theme across all our sites?

And then if we have a large subset of sites running on a special child theme already, would deploying a banner via child theme still make sense? Of course, since we run most of our sites on multisites, that simplifies the deployment of child themes for special cases like this...
