### ISSUE TITLE
ASU Header Logo and Content Area Not Aligned

### ISSUE THREAD

**Issue by wmcconnell** [asu-ke-web-services/UDS-WordPress-Theme#75]
Our content area is not left-aligning with the ASU logo:

<img width="606" alt="Screen Shot 2020-12-02 at 9 50 10 AM" src="https://user-images.githubusercontent.com/31013359/100905230-10ad0000-3485-11eb-82b2-2eb213298965.png">

We need to determine if the problem is in the header markup, or the padding/margins from the body containers or rows and adjust accordingly.

**Comment by wmcconnell** [comment]
It looks like the issue is that the container that wraps the main menu area has the default Bootstrap padding removed. The main menu area is wrapped with `<div id="header-main" class="container">`, and the CSS has removed all padding on `#header-main`. Because the content area is using the standard Bootstrap rows and columns, there is some default padding there.

Removing the `padding: 0` from `#header-main` in the inspector makes things line up appropriately, so removing that padding rule from our SCSS should fix this issue.

<img width="523" alt="padding-fix" src="https://user-images.githubusercontent.com/31013359/100908458-bf067480-3488-11eb-9b76-dcbb6c95374b.png">

**Comment by nathan-rollins** [comment]
However, that changes the width of the header from 1224px to 1200px. According to the Storybook implementation, 1224px is the correct width. We need to confirm this with Steve/the Web Standards group, but if so, the problem is not in the header, it is in the content area, which has padding applied that needs to removed (set to 0).
